lane :test do
  zeeva_discord(
    server_token: "",
    client_id: "",
    channel_id: "",
    build_name: "Android Production Build",
    platform_code: "Android",
    build_type: "Debuggable Build",
    title: "This is the Message Title",
    message: "This is the Message Body"
  )
end
